### ISSUE TITLE
Bulletin/Blog using date files?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Site#15]
https://novelist.xyz/tech/hugo-data-files/
https://middlemanapp.com/advanced/data-files/

We already use a [data file for the whitelist](https://github.com/gridcoin-community/Gridcoin-Site/blob/master/data/whitelist.yml) which severely reduced the amount of maintenance effort requires to change the whitelist (no more manual html work).

A problem with using yml data files that I ran into was the inability to embed HTML within the goal and sponsor fields of the whitelist.yml file (due to use of " or ' when specifying the URL within the hyperlink, both of which broke the parsing of the yml file).

blog.yml example format:
```
posts:
- title: "Example blog post title"
  link_primary_url: "https://google.com"
  link_primary_text: "Primary link text"
  link_secondary_url: "https://google.com"
  link_secondary_text: "Primary link text"
  content: "Blog post content."
- title: "Example blog post title"
  link_primary_url: "https://google.com"
  link_primary_text: "Primary link text"
  link_secondary_url: "https://google.com"
  link_secondary_text: "Primary link text"
  content: "Blog post content."
```

blog.htm.erb example format:
```
---
title: "Gridcoin - Blog"
description: "This blog is for official announcements and important community updates."
---
    <section  data-background-color="black" style="overflow-x: hidden;">
        <!-- BOINC Content -->
        <div class="container">
            <div class="row">
                <% data.blog.posts.each do |post| %>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h4><%= post.title %></h4>
                        <p><%= post.content %></p>
                        <a href="<%= post.link_primary_url %>"><%= post.link_primary_text %></a>
                        <a href="<%= post.link_secondary_url %>"><%= post.link_secondary_text %></a>
                    </div>
                <% end %>
            </div>
        </div>
    </section>
```
